# 컴퓨터들
services:

  # 데이터베이스컴퓨터
  my-database:

    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydocker'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306


  # 서버컴퓨터
  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/myfolder/backend/src
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
  
  # 프론트엔드컴퓨터
  # my-frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/src:/myfolder/frontend/src
  #     - ./frontend/public:/myfolder/frontend/public
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./frontend/.env
