# 컴퓨터들
services:

  # 서버컴퓨터
  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
      # - ./backend/src:/myfolder/backend/src
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env.dev
  
  # 프론트엔드컴퓨터
  my-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
      # - ./frontend/src:/myfolder/frontend/src
      # - ./frontend/public:/myfolder/frontend/public
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.dev
